---
title: "Data Manipulation"
output: github_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

##Import datasets
```{r}
litters_data = read_csv("./data/FAS_litters.csv")
litters_data = janitor::clean_names(litters_data)

pups_data = read_csv("./data/FAS_pups.csv")
pups_data = janitor::clean_names(pups_data)
```

## Selecting!!

```{r}
select(litters_data, group, litter_number)

select(litters_data, group, litter_number, gd0_weight)

select(litters_data, group, litter_number, gd0_weight, starts_with("pups"))

select(litters_data, litter_number, group, gd0_weight)

select(litters_data, litter_number, group, everything())

select(litters_data, -group)

select(litters_data, litter_number, gd0_weight:pups_born_alive)

select(litters_data, GROUP = group, litter_number)

rename(litters_data, GROUP = group)
#doesn't select, just renames
```

##Filtering!!

```{r}
filter(litters_data, group == "Mod8")

filter(litters_data, gd_of_birth ==20)

filter(litters_data, gd_of_birth < 20)

filter(litters_data, pups_born_alive < 6)

filter(litters_data, pups_born_alive < 6, group == "Con7")

#filter(litters_data, group == "Con7" | group == "Mod8")
filter(litters_data, group %in% c("Con7", "Mod8"))

filter(litters_data, gd0_weight + gd18_weight < 70)

#don't do this:
#filter(litters_data, !is.na(gd0_weight))

drop_na(litters_data, gd0_weight)
#second parameter is optional to drop na's in a certain column, otherwise drops all rows that aren't complete
```

## Mutate

```{r}
mutate(
  litters_data, 
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group),
  group = str_to_upper(group))

#Use mutate to modify variables
```

## Arrange

```{r}
arrange(litters_data, pups_born_alive)
#put in order of pups born alive

arrange(litters_data, desc(pups_born_alive))

arrange(litters_data, pups_born_alive, gd0_weight)
```

## pipe ...

Create a collection of commands

```{r}
litters_data_raw = read_csv("./data/FAS_litters.csv",
  col_types = "ccddiiii")
litters_data_clean_names = janitor::clean_names(litters_data_raw)
litters_data_selected_cols = select(litters_data_clean_names, -pups_survive)
litters_data_with_vars = 
  mutate(
    litters_data_selected_cols, 
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group))
litters_data_with_vars_without_missing = 
  drop_na(litters_data_with_vars, wt_gain)
litters_data_with_vars_without_missing
```

```{r}
litters_data_clean = 
  drop_na(
    mutate(
      select(
        janitor::clean_names(
          read_csv("./data/FAS_litters.csv", col_types = "ccddiiii")
          ), 
      -pups_survive
      ),
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)
    ),
  wt_gain
  )

litters_data_clean
```

```{r}
litters_data = 
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>% 
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)) %>% 
  drop_na(wt_gain) 

litters_data
```

```{r}
litters_data %>% pull(gd0_weight) %>% mean()
```


